source_url:
  type: string
  default: ""
source_token:
  type: string
  default: ""
iframe_height:
  type: string
  default: 600px
composer_icon_location:
  type: enum
  default: toolbar
  choices:
    - toolbar
    - popup menu
    - both
